"""v5

Revision ID: c92f2a2f1817
Revises: 595c6b83daa5
Create Date: 2023-11-25 23:09:53.907867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92f2a2f1817'
down_revision = '595c6b83daa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linear_accelerator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('operation_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('operation_end_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('pause_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pause_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linear_accelerator', schema=None) as batch_op:
        batch_op.drop_column('pause_end_time')
        batch_op.drop_column('pause_start_time')
        batch_op.drop_column('operation_end_time')
        batch_op.drop_column('operation_start_time')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
